Feature/65 allow admin user to configure the main articles section
yuremboo/UJP-Sports-Hub-UI pull request #20
Opened 2022-09-25 10:44 UTC by OksanaOlesja

2022-09-25 12:33 UTC, NastiaChaikovska requested changes
don't rewrite existing styles

2022-09-25 12:33 UTC, NastiaChaikovska commented on src/index.js
> +                    <Route path="admin/home" element={<AdminHomePage/>}/>
this is unnecessary

2022-09-26 10:58 UTC, AndriyBarskyi approved these changes

2022-09-26 14:56 UTC, NastiaChaikovska approved these changes

2022-09-26 15:08 UTC, merged